server:
  port: 8081

spring:
  cloud:
    config:
      server:

        git:
          uri: https://github.com/Lets-Travel-Well/are-you-alone-config-file
          default-label: main
        encrypt: #모든 설정 정보를 암호화 시키겠다는 의미
          enabled: false

# actuator 설정
management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    shutdown:
      enabled: true

encrypt: #암호화 시키는데 사용하는 key값
  key: key-brain