server:
  port: 8081

spring:
  cloud:
    config:
      server:

        git:
          uri: https://github.com/Lets-Travel-Well/are-you-alone-config-file
          default-label: main

# actuator 설정
management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    shutdown:
      enabled: true